export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  SALES: "/sales",
  PROCUREMENT: "/procurement",
  INVENTORY: "/inventory",
  SUPPLIERS: "/suppliers",
  ACCOUNTING: "/accounting",
  CRM: "/crm",
  Hr: "/hr",
  FixedAssets: "/fasset",
  CompanySetup: "/companySetup",
  UserManagement: "/userManagement",
  BankAccountPage: "/BankAccountPage",
};
