export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup", 
  DASHBOARD: "/dashboard",
  SALES: "/sales",
  PROCUREMENT: "/procurement",
  INVENTORY: "/inventory",
  SUPPLIERS: "/suppliers",
  ACCOUNTING: "/accounting",
  CRM: "/crm",
  Hr: "/hr",
  FixedAssets: "/fasset",
  CompanySetup: "/companySetup",
  UserManagement: "/userManagement",
  BankManagement: "/bank-management",
  ModeOfPaymentSetup: "/mode-of-payment-setup",
  PaymentEntry: "/payment-entry",
  CurrencyConversion: "/currency-conversion",
  CustomerGroup: "/customer-group",
  taxMaintenance: "/Tax-Maintenance",
  expenseManagement: "/Expense-Management",
  EmailTemplate: "/Email-Template",
  performance: "/performance",

};
