export type SelectedStockItem = {
  itemCode: string;
  itemName?: string;
  description: string;
  packingSize?: number;
  packingUnit?: number;
  batchNo?: string;
  mfgDate?: string;
  expiryDate?: string;
  qty?: number;
  price?: number;     
  valuation_rate?: number;
  sellingPrice?: number;
  purchasePrice?: number;
  warehouse?: string;
  vatRate?: number;
  vatCode?: string;
  taxInfo?: any[];
  isServiceItem?: boolean;
  piecesPerBox?: number;
};